# Generated by Django 3.0.6 on 2020-09-22 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('munchkin', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munchkin.Game'),
        ),
        migrations.AddField(
            model_name='membership',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='gamer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
