# Generated by Django 3.0.6 on 2020-09-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basegame',
            name='end',
            field=models.DateTimeField(verbose_name='время окончания игры'),
        ),
    ]
