# Generated by Django 3.0.6 on 2020-09-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200916_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basegame',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время окончания игры'),
        ),
    ]
