# Generated by Django 3.0.6 on 2020-10-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'карта',
                'verbose_name_plural': 'карты',
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('door', 'Дверь'), ('treasure', 'Сокровище')], max_length=25, unique=True, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'тип карты',
                'verbose_name_plural': 'типы карт',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('onetime', 'Разовая'), ('head', 'Головняк'), ('armor', 'Бронь'), ('foot', 'Обувка'), ('weapon', 'Оружие'), ('other', 'Другое')], max_length=25, unique=True, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'тип шмотки',
                'verbose_name_plural': 'типы шмоток',
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='уровень монстра')),
                ('is_undead', models.BooleanField(default=False, verbose_name='нежить')),
                ('treasure_count', models.PositiveSmallIntegerField(verbose_name='кол-во сокровищ за победу')),
                ('win_levels', models.PositiveSmallIntegerField(verbose_name='кол-во уровней за победу')),
            ],
            options={
                'verbose_name': 'монстр',
                'verbose_name_plural': 'монстры',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_large', models.BooleanField(default=False, verbose_name='большая')),
                ('damage', models.PositiveSmallIntegerField(verbose_name='урон шмотки')),
                ('hand_count', models.PositiveSmallIntegerField(verbose_name='кол-во рук')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='mainapp.ItemType', verbose_name='тип шмотки')),
            ],
            options={
                'verbose_name': 'шмотка',
                'verbose_name_plural': 'шмотки',
            },
        ),
        migrations.CreateModel(
            name='Effects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(max_length=100, verbose_name='наименование метода эффекта')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='effects', to='mainapp.Card', verbose_name='карта')),
            ],
            options={
                'verbose_name': 'эффект',
                'verbose_name_plural': 'эффекты',
            },
        ),
        migrations.CreateModel(
            name='CardSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('item', 'Шмотка'), ('level', 'Уровень'), ('other', 'Другое'), ('monster', 'Монстр'), ('weakness', 'Проклятие'), ('mod', 'Модиффикация'), ('klass', 'Класс'), ('race', 'Раса')], max_length=25, unique=True, verbose_name='наименование')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_types', to='mainapp.CardType', verbose_name='подтип карты')),
            ],
            options={
                'verbose_name': 'подтип карты',
                'verbose_name_plural': 'подтипы карт',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Item', verbose_name='шмотка'),
        ),
        migrations.AddField(
            model_name='card',
            name='monster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Monster', verbose_name='монстр'),
        ),
        migrations.AddField(
            model_name='card',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='mainapp.CardSubType', verbose_name='подтип карты'),
        ),
    ]
